version: '3.8'

services:
  frontend:
    image: mayur2808/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: mayur2808/backend:latest
    ports:
      - "8081:3001"
    restart: unless-stopped
