version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3001
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8081:3001"
    restart: unless-stopped
